- docs/UserGuide (Template).md
- docs/UserGuide.md
> Add UG from Google Docs draft

- docs/team/isabelchong.md
> Add Skeletal PPP (Isabel)

- docs/_config.yml
It contained some placeholder text from AB3, needed to replace to our own project.
> Modify _config.yml

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
- src/test/java/seedu/address/testutil/StudentUtil.java
After this merge, EditCommand can handle edits on `module` field. 
There must exist at least one `module` for a `Student`.
Closes #56
> Update EditCommand and EditCommandTest

- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
> Feat: View command

- docs/AboutUs.md
- docs/DeveloperGuide.md
- Removed filler email in AboutUs to replace it with our actual emails
- Replaced student information in DG glossary to match our implementation
> Update AboutUs and DG

- src/main/java/tfifteenfour/clipboard/ui/MainWindow.java
When student photo is uploaded to CLIpboard, student view card would automatically refresh to reflect newly added photo.
> Fix upload command

- docs/AboutUs.md
- docs/UserGuide.md
- src/main/java/tfifteenfour/clipboard/logic/commands/EditCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ModuleCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/AddCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/EditCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/ModuleCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
- src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
- src/main/java/tfifteenfour/clipboard/model/student/Course.java
- src/main/java/tfifteenfour/clipboard/model/student/ModuleCode.java
- src/main/java/tfifteenfour/clipboard/model/student/Student.java
- src/main/java/tfifteenfour/clipboard/model/student/StudentTakingModulePredicate.java
- src/main/java/tfifteenfour/clipboard/model/util/SampleDataUtil.java
- src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedModuleCode.java
- src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedStudent.java
- src/test/java/tfifteenfour/clipboard/logic/commands/ModuleCommandTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/AddCommandParserTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/EditCommandParserTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/ModuleCommandParserTest.java
- src/test/java/tfifteenfour/clipboard/model/student/ModuleCodeTest.java
- src/test/java/tfifteenfour/clipboard/model/student/StudentTakingModulePredicateTest.java
- src/test/java/tfifteenfour/clipboard/testutil/EditStudentDescriptorBuilder.java
- src/test/java/tfifteenfour/clipboard/testutil/StudentBuilder.java
- src/test/java/tfifteenfour/clipboard/testutil/StudentUtil.java
Add Module command which filters the students according to the module keyword inputted by the user.
Format: module `MODULE CODE`
Examples: module CS2103T
> Add Module Command

- src/main/java/tfifteenfour/clipboard/ui/CommandBox.java
- src/main/resources/view/CommandBox.fxml
Allow user to scroll through past inputs in command box by pressing UP and DOWN keys
> Add browse command history functionality

- src/main/java/tfifteenfour/clipboard/ui/StudentCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/StudentListCard.fxml
> Edit student list card to display name, module, and tag

- src/main/java/tfifteenfour/clipboard/logic/CircularBuffer.java
- src/main/java/tfifteenfour/clipboard/logic/LogicManager.java
- src/main/java/tfifteenfour/clipboard/logic/commands/AddCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ClearCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/Command.java
- src/main/java/tfifteenfour/clipboard/logic/commands/CommandResult.java
- src/main/java/tfifteenfour/clipboard/logic/commands/DeleteCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/EditCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ExitCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/FindCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/HelpCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ListCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ModuleCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/RemarkCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/UndoCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/UploadCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ViewCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/UploadCommandParser.java
- src/main/java/tfifteenfour/clipboard/model/Model.java
- src/main/java/tfifteenfour/clipboard/model/ModelManager.java
- src/main/java/tfifteenfour/clipboard/model/Roster.java
- src/main/java/tfifteenfour/clipboard/ui/MainWindow.java
- src/main/java/tfifteenfour/clipboard/ui/StudentListPanel.java
- src/test/java/tfifteenfour/clipboard/logic/commands/AddCommandTest.java
- src/test/java/tfifteenfour/clipboard/logic/commands/CommandResultTest.java
- src/test/java/tfifteenfour/clipboard/logic/commands/CommandTestUtil.java
- src/test/java/tfifteenfour/clipboard/logic/commands/ExitCommandTest.java
- src/test/java/tfifteenfour/clipboard/logic/commands/HelpCommandTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/UploadCommandParserTest.java
Undo up to **5 previous commands**.  (Capped at 5 tentatively. Need to monitor the effect on performance and adjust accordingly)
> Feat: Undo command

- src/main/java/tfifteenfour/clipboard/ui/MainWindow.java
- src/main/java/tfifteenfour/clipboard/ui/NavigationBar.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/ActiveGroupTab.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/ActiveModuleTab.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/ActiveStudentTab.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/InactiveGroupTab.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/InactiveModuleTab.java
- src/main/java/tfifteenfour/clipboard/ui/pagetab/InactiveStudentTab.java
- src/main/resources/view/CourseListCard.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/GroupListCard.fxml
- src/main/resources/view/GroupTab.fxml
- src/main/resources/view/InactiveGroupTab.fxml
- src/main/resources/view/InactiveModuleTab.fxml
- src/main/resources/view/InactiveStudentTab.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ModuleTab.fxml
- src/main/resources/view/NavigationBar.fxml
- src/main/resources/view/StudentListCard.fxml
- src/main/resources/view/StudentTab.fxml
- src/main/resources/view/StudentViewCard.fxml
Add page tabs and navigation bar so that it is easier for user to know which page they are at
> Add page tab GUI

- src/main/java/tfifteenfour/clipboard/ui/MainWindow.java
- src/main/java/tfifteenfour/clipboard/ui/NavigationBar.java
- src/main/resources/view/AbsentListCard.fxml
- src/main/resources/view/AttendanceListCard.fxml
Reference to #121 and slight tweak to colour scheme
> Update GUI for session command

- src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteCourseCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteGroupCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteSessionCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteStudentCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/DeleteCommandParser.java
- src/main/java/tfifteenfour/clipboard/model/course/Course.java
- src/main/java/tfifteenfour/clipboard/model/course/Group.java
Some delete commands are not working, updated code to make it working
- `delete group`
- `delete student`
== Ready to merge ==
> Update delete commands

- src/main/java/tfifteenfour/clipboard/logic/commands/findcommand/FindStudentCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/FindCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/predicates/StudentParticularsContainsPredicate.java
Generalised find command to detect name and SID for the keywords
```
find student <name>
```
```
find student <sid>
```
> Update find command to be more generalised

- src/main/java/tfifteenfour/clipboard/logic/commands/sortcommand/SortCommand.java
Fixes sort command. It was implemented but accidentally removed while resolving a merge conflict... oops. lol
> Fix sort command

- src/main/java/tfifteenfour/clipboard/logic/LogicManager.java
- src/main/java/tfifteenfour/clipboard/logic/parser/EditCommandParser.java
- src/main/java/tfifteenfour/clipboard/model/course/Group.java
Fixed before but somehow it got reverted by some other pr...?
Closes #172 , #174
> Fix edit command 

- src/main/java/tfifteenfour/clipboard/logic/commands/findcommand/FindCourseCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/FindCommandParser.java
> Fix error message for `find`

- src/main/java/tfifteenfour/clipboard/logic/parser/MarkCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
- src/main/java/tfifteenfour/clipboard/logic/parser/UnmarkCommandParser.java
> Adds more detailed error message to `mark` and `unmark`

- src/main/java/tfifteenfour/clipboard/MainApp.java
- src/main/java/tfifteenfour/clipboard/logic/parser/FindCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/RemarkCommandParser.java
- src/main/java/tfifteenfour/clipboard/ui/MainWindow.java
Related to #180
Also fix bug for when UI does not refresh when undo command is called after clearing session/task page
> Fix bug relating to clear command not clearing UI elements

- src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
- src/main/java/tfifteenfour/clipboard/model/course/Course.java
- src/main/java/tfifteenfour/clipboard/model/course/Group.java
- src/main/java/tfifteenfour/clipboard/model/course/Session.java
- src/main/java/tfifteenfour/clipboard/model/task/Task.java
Also allows group/session/task names to have special characters 
Closes #168
> Fix for #168

- src/main/java/tfifteenfour/clipboard/logic/parser/SortCommandParser.java
Add more detailed error message for sort
Closes #213
> Fix for #213

- docs/UserGuide.md
Closes #218 
=READY=
feel free to make suggestion
> Adds guide to user guide

- docs/team/isabelchong.md
> Update Isabel's PPP

- src/main/java/tfifteenfour/clipboard/MainApp.java
- src/main/java/tfifteenfour/clipboard/logic/commands/ExitCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditStudentCommand.java
as per title.
fixes #182 
READY
> Rename "Address Book" to CLIpboard or student roster.

- docs/UserGuide.md
- src/main/java/tfifteenfour/clipboard/logic/parser/CommandTargetType.java
- src/main/java/tfifteenfour/clipboard/logic/parser/FindCommandParser.java
as described in #240 , also fixed error message
READY
> fix UG for `find` command

- src/main/java/tfifteenfour/clipboard/logic/commands/addcommand/AddSessionCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/addcommand/AddTaskCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditCourseCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditGroupCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditSessionCommand.java
- src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditTaskCommand.java
- src/main/java/tfifteenfour/clipboard/logic/parser/AddCommandParser.java
- src/main/java/tfifteenfour/clipboard/logic/parser/EditCommandParser.java
- src/main/java/tfifteenfour/clipboard/model/course/Group.java
- src/main/java/tfifteenfour/clipboard/model/course/Session.java
- src/main/java/tfifteenfour/clipboard/model/task/Task.java
- src/test/java/tfifteenfour/clipboard/logic/commands/CommandTestUtil.java
- src/test/java/tfifteenfour/clipboard/logic/commands/addcommand/AddStudentCommandTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/AddCommandParserTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/CommandParserTestUtil.java
- src/test/java/tfifteenfour/clipboard/logic/parser/EditCommandParserTest.java
- src/test/java/tfifteenfour/clipboard/logic/parser/ParserUtilTest.java
> add testing for parsers

- docs/UserGuide.md
==ready to merge==
You can refer to the UG [here](https://github.com/peaol/tp/blob/branch-UpdateUGFinal/docs/UserGuide.md#glossary)
Changes made:
- Add glossary and student command field table
- Mention that course/group/task/session can have special characters
- Add design decisions
> Fix non PE-D documentation bugs in UG

- docs/DeveloperGuide.md
==Ready to merge==
You can view the DG [here](https://github.com/peaol/tp/blob/branch-DG/docs/DeveloperGuide.md)
Added in test cases for the following sections under `Appendix: Instructions for manual testing`:
- Students Page Commands
- Session Page Commands
- Attendance Page Commands
> Update DG with Test Cases for Manual Testing Part 2/2

- docs/AboutUs.md
- docs/team/isabelchong.md
> PPP - Isabel

- docs/team/isabelchong.md
> Update PPP - Isabel (format update)

- src/main/java/tfifteenfour/clipboard/MainApp.java
> Update version number in MainApp
